In [1]:
import numpy as np
import cv2 as cv
from skimage.io import imread
from skimage import feature
from skimage.transform import integral_image
from skimage.viewer import ImageViewer

C:\Users\panto\AppData\Local\Continuum\anaconda3\lib\site-packages\skimage\viewer\utils\core.py:10: UserWarning: Recommended matplotlib backend is `Agg` for full skimage.viewer functionality.
  warn("Recommended matplotlib backend is `Agg` for full "


In [2]:
image = cv.imread('1.jpg', cv.IMREAD_GRAYSCALE)

In [3]:
g = feature.greycomatrix(image, distances=[1, 2, 3, 4, 8, 16, 32], angles=[-np.pi/4, 0, np.pi/4, np.pi/2], levels=256, symmetric=True, normed=True)

In [4]:
feature.greycoprops(g, 'contrast')

array([[  10.80764142,    8.08697415,   13.0096116 ,    8.07265424],
       [  10.80764142,   19.39982022,   13.0096116 ,   19.34078039],
       [  29.52094953,   33.35280995,   31.02355405,   33.1807063 ],
       [  52.82662018,   49.87661063,   56.26339145,   49.53400741],
       [ 170.29125499,  160.41467724,  183.72692617,  158.54989898],
       [ 478.02122448,  527.62438032,  520.45404124,  516.19542382],
       [1397.94533949, 1460.97761066, 1540.89974522, 1413.94878494]])

In [5]:
feature.greycoprops(g, 'dissimilarity')

array([[ 2.47300294,  2.12727299,  2.71663152,  2.12343891],
       [ 2.47300294,  3.2718649 ,  2.71663152,  3.2654294 ],
       [ 3.9486245 ,  4.16970916,  4.03974378,  4.15337148],
       [ 5.08045861,  4.96075935,  5.23768625,  4.93353558],
       [ 8.65099872,  8.44038301,  9.00819608,  8.35773707],
       [14.38390694, 15.18746181, 15.08619485, 14.93585605],
       [25.50059597, 26.21176079, 26.9765385 , 25.57667171]])

In [6]:
feature.greycoprops(g, 'homogeneity')

array([[0.33591124, 0.37499247, 0.31408776, 0.37546492],
       [0.33591124, 0.27821966, 0.31408776, 0.27863215],
       [0.24634992, 0.23689361, 0.24245596, 0.23777095],
       [0.21284659, 0.21637204, 0.20831639, 0.21748044],
       [0.15867078, 0.16017437, 0.15347421, 0.16187396],
       [0.11517703, 0.11054379, 0.11020682, 0.11281813],
       [0.07598362, 0.07369711, 0.07154879, 0.07582791]])

In [7]:
feature.greycoprops(g, 'ASM')

array([[4.87596451e-04, 5.65077932e-04, 4.46031261e-04, 5.65910369e-04],
       [4.87596451e-04, 3.79562358e-04, 4.46031261e-04, 3.80044847e-04],
       [3.25872975e-04, 3.11644738e-04, 3.19444231e-04, 3.12603823e-04],
       [2.71595475e-04, 2.76281724e-04, 2.64284676e-04, 2.77623090e-04],
       [1.88041774e-04, 1.90237441e-04, 1.80579387e-04, 1.92310438e-04],
       [1.28491811e-04, 1.22247823e-04, 1.21841898e-04, 1.24683834e-04],
       [7.83702633e-05, 7.54974848e-05, 7.27554466e-05, 7.78174425e-05]])

In [8]:
feature.greycoprops(g, 'energy')

array([[0.02208159, 0.02377137, 0.02111945, 0.02378887],
       [0.02208159, 0.01948236, 0.02111945, 0.01949474],
       [0.01805195, 0.01765346, 0.017873  , 0.01768061],
       [0.01648015, 0.01662172, 0.01625683, 0.01666203],
       [0.01371283, 0.01379266, 0.01343798, 0.0138676 ],
       [0.01133542, 0.01105657, 0.0110382 , 0.01116619],
       [0.0088527 , 0.00868893, 0.00852968, 0.00882142]])

In [9]:
feature.greycoprops(g, 'correlation')

array([[0.99835536, 0.99876931, 0.99802028, 0.99877156],
       [0.99835536, 0.99704768, 0.99802028, 0.997057  ],
       [0.9955079 , 0.99492426, 0.99527925, 0.99495131],
       [0.99196195, 0.99240959, 0.99143901, 0.99246344],
       [0.97409246, 0.97558734, 0.97204837, 0.97588165],
       [0.92729363, 0.91970553, 0.92083932, 0.92150774],
       [0.78751383, 0.77771616, 0.76578037, 0.78515136]])

In [10]:
image.shape

(3286, 4096)